sudo: false
language: nodejs
node_js:
  - 8
  - "stable"

git:
  depth:
    1

addons:
    apt:
      update: true

before_script:
  - node -v
  - yarn
#  - yarn build:prod

script:
  - yarn test

after_success:
  - "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"

#deploy:
#  - provider: releases
#    api_key: $GITHUB_TOKEN
#    file_glob: true
#    file: "kresst-*.tgz"
#    skip_cleanup: true
#    on:
#      tags: true
#  - provider: npm
#    skip_cleanup: true
#    email: "youremail@example.com"
#    api_key: $NPM_TOKEN
#    on:
#      tags: true
